# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(max_length=1000, verbose_name='Alias')),
                ('horastotales', models.IntegerField(default=0, verbose_name='Horas Totales')),
                ('creditos', models.FloatField(default=0, verbose_name='Creditos')),
                ('horassemanales', models.IntegerField(default=0, verbose_name='Horas Semanales')),
                ('cupo', models.IntegerField(default=0, verbose_name='Cupo')),
                ('paralelo', models.CharField(max_length=10, verbose_name='Paralelo')),
                ('fechamatriculacion', models.DateField(blank=True, null=True)),
                ('fechamatriculacionfin', models.DateField(blank=True, null=True)),
                ('fechaordinariainicio', models.DateField(blank=True, null=True)),
                ('fechaordinariafin', models.DateField(blank=True, null=True)),
                ('fechaextraordinariainicio', models.DateField(blank=True, null=True)),
                ('fechaextraordinariafin', models.DateField(blank=True, null=True)),
                ('fechaespecialinicio', models.DateField(blank=True, null=True)),
                ('fechaespecialfin', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignaturaMalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('optativa', models.BooleanField(default=False, verbose_name='Optativa')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Asignatura', verbose_name='Asignatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'verbose_name': 'Ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoordinadorCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Carrera', verbose_name='Carrera')),
            ],
            options={
                'ordering': ['carrera__facultad'],
            },
        ),
        migrations.CreateModel(
            name='EjeFormativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombrecliente', models.CharField(default='Peru', max_length=100, verbose_name='Producto')),
                ('ruccliente', models.CharField(default='', max_length=15, verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'verbose_name': 'Factura',
                'ordering': ['nombrecliente'],
            },
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.CharField(default='', max_length=100, verbose_name='Producto')),
                ('cantidad', models.FloatField(default=0, verbose_name='Cantidad')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Factura')),
            ],
            options={
                'verbose_name_plural': 'Facturas Detalle',
                'verbose_name': 'Factura Detalle',
                'ordering': ['factura'],
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraduadoMecanismoTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.TextField(default='', verbose_name='Nombre')),
                ('codigosniese', models.CharField(default='', max_length=2, verbose_name='Codigo SNIESE')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre Grupo')),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Facultad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Inscripcion')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Carrera', verbose_name='Carrera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionMalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Inscripcion')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Inscripcion', verbose_name='Inscripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('nombre', models.CharField(blank=True, default='nombre', max_length=100, null=True, verbose_name='Nombre')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Carrera', verbose_name='Carrera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('final', models.DateTimeField(verbose_name='Fecha final')),
                ('asignaturamalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.AsignaturaMalla', verbose_name='Asignatura Malla')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatriculaTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fechainscripcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripcion')),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (8, 'PENDIENTE DE PAGO'), (2, 'MATRICULADO'), (3, 'RETIRADO'), (4, 'RECHAZADO'), (9, 'ANULADO '), (6, 'REPROBADO'), (5, 'ELIMINADO'), (7, 'APROBADO')], default=1, verbose_name='Estado de Matricula')),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Nota')),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AlternativaTitulacion')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Inscripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MecanismoTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modalidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Modalidad', verbose_name='Modalidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NivelMalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='Peru', max_length=100, verbose_name='Pais')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='pais/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'verbose_name': 'Pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=10, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'PeriodoS',
                'verbose_name': 'Periodo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoGrupoTitulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=500, verbose_name='Periodo Titulacion')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Observacion Periodo Titulacion')),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('creditomin', models.FloatField(default=0)),
                ('creditomax', models.FloatField(default=0)),
                ('horasmodelotitumin', models.IntegerField(default=0)),
                ('horasmodelotitumax', models.IntegerField(default=0)),
                ('porcentajeurkund', models.FloatField(blank=True, null=True, verbose_name='Porcentaje Plagio')),
                ('porcientoaprobado', models.FloatField(default=0, verbose_name='Porcentaje de aprobacion a cumplir')),
                ('nrevision', models.IntegerField(blank=True, default=2, null=True, verbose_name='Número')),
                ('abierto', models.BooleanField(default=True, verbose_name='Periodo abierto')),
                ('valortitulacion', models.FloatField(default=0, verbose_name='Valor titulacion')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='Periodo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(default='', max_length=30, verbose_name='Nombres')),
                ('apellido1', models.CharField(default='', max_length=30, verbose_name='Apellido 1')),
                ('apellido2', models.CharField(default='', max_length=30, verbose_name='Apellido 2')),
                ('cedula', models.CharField(default='', max_length=10, null=True, verbose_name='Cedula')),
                ('pasaporte', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Pasaporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='Profesor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha final')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Materia', verbose_name='Materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Profesor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name_plural': 'ProfesorMaterias',
                'verbose_name': 'ProfesorMateria',
                'ordering': ['materia'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Provincia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'verbose_name': 'Provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTitulaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Titulacion')),
                ('codigo', models.CharField(max_length=100, verbose_name='Codigo')),
                ('caracteristica', models.CharField(max_length=2000, verbose_name='Caracteristicas')),
                ('mecanismotitulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GraduadoMecanismoTitulacion', verbose_name='Mecanismo Titulación')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='pais',
            unique_together=set([('nombre',)]),
        ),
        migrations.AddField(
            model_name='nivel',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='Periodo Lectivo'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Nivel', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='materia',
            name='paralelomateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Paralelo', verbose_name='Paralelo Materia'),
        ),
        migrations.AddField(
            model_name='inscripcionmalla',
            name='malla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Malla', verbose_name='Malla'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='grupotitulacion',
            name='periodogrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.PeriodoGrupoTitulacion'),
        ),
        migrations.AddField(
            model_name='graduadomecanismotitulacion',
            name='mecanismotitulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.MecanismoTitulacion', verbose_name='Mecanismo'),
        ),
        migrations.AddField(
            model_name='coordinadorcarrera',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Modalidad', verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='coordinadorcarrera',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='Periodo lectivo'),
        ),
        migrations.AddField(
            model_name='coordinadorcarrera',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='coordinadorcarrera',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Facultad', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='asignaturamalla',
            name='ejeformativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.EjeFormativo', verbose_name='Eje Formativo'),
        ),
        migrations.AddField(
            model_name='asignaturamalla',
            name='malla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Malla', verbose_name='Malla'),
        ),
        migrations.AddField(
            model_name='asignaturamalla',
            name='nivelmalla',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.NivelMalla', verbose_name='Nivel Malla'),
        ),
        migrations.AddField(
            model_name='alternativatitulacion',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Carrera', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='alternativatitulacion',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Facultad'),
        ),
        migrations.AddField(
            model_name='alternativatitulacion',
            name='grupotitulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoTitulacion', verbose_name='Grupo Titulacion'),
        ),
        migrations.AddField(
            model_name='alternativatitulacion',
            name='tipotitulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.TipoTitulaciones', verbose_name='Tipo Titulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='facturaproducto',
            unique_together=set([('factura', 'producto')]),
        ),
        migrations.AlterUniqueTogether(
            name='canton',
            unique_together=set([('nombre',)]),
        ),
    ]
