# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'TipoReactivo',
                'verbose_name_plural': 'TipoReactivos',
                'ordering': ['nombre'],
            },
        ),
    ]
