# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0002_tiporeactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Descripcion')),
                ('cantidadopcionesmin', models.IntegerField(default='1', verbose_name='Cantidad opciones minima')),
                ('cantidadopcionesmax', models.IntegerField(default='4', verbose_name='Cantidad opciones maxima')),
                ('cantidadrespuestasmin', models.IntegerField(default='1', verbose_name='Cantidad respuestas minima')),
                ('cantidadrespuestasmax', models.IntegerField(default='4', verbose_name='Cantidad respuestas maxima')),
                ('notamin', models.DecimalField(decimal_places=2, default='1.00', max_digits=4, verbose_name='Nota Reactivo minima')),
                ('notamax', models.DecimalField(decimal_places=2, default='1.00', max_digits=4, verbose_name='Nota Reactivo maxima')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivo/%Y/%m/%d')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Profesor', verbose_name='Profesor')),
                ('tiporeactivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.TipoReactivo', verbose_name='Tipo reactivo')),
            ],
            options={
                'verbose_name': 'Formato',
                'ordering': ['estado'],
                'verbose_name_plural': 'Formatos',
            },
        ),
    ]
