# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0005_atributoreactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPreguntaReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('abreviatura', models.CharField(default='', max_length=20, verbose_name='Abreviatura')),
                ('activo', models.NullBooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'TipoPreguntaReactivos',
                'verbose_name': 'TipoPreguntaReactivo',
                'ordering': ['activo', 'id'],
            },
        ),
    ]
