# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0006_tipopreguntareactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCoordinadorDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('estadoinicial', models.NullBooleanField(default=True, verbose_name='estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=True, verbose_name='estadofinal')),
                ('coordinador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.CoordinadorCarrera', verbose_name='coordinador')),
            ],
            options={
                'verbose_name_plural': 'AsignacionCoordinadorDocentes',
                'verbose_name': 'AsignacionCoordinadorDocente',
            },
        ),
        migrations.CreateModel(
            name='CronogramaPlanificacionExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('periodo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='Periodo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name_plural': 'CronogramaPlanificaciones',
                'verbose_name': 'CronogramaPlanificacion',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCarreraExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('carrera', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Carrera', verbose_name='carrera')),
            ],
            options={
                'verbose_name_plural': 'GrupoCarreraExamenes',
                'verbose_name': 'GrupoCarreraExamen',
                'ordering': ['grupofacultad'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFacultadExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('facultad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Facultad', verbose_name='Cronograma')),
                ('grupocronograma', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.CronogramaPlanificacionExamen', verbose_name='Cronograma')),
            ],
            options={
                'verbose_name_plural': 'GrupoFacultadExamenes',
                'verbose_name': 'GrupoFacultadExamen',
                'ordering': ['grupocronograma'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFormatoReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('formatoreactivo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.FormatoReactivo', verbose_name='Formato')),
                ('grupocronograma', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.CronogramaPlanificacionExamen', verbose_name='Cronograma')),
            ],
            options={
                'verbose_name_plural': 'GrupoFormatoReactivos',
                'verbose_name': 'GrupoFormatoReactivo',
                'ordering': ['grupocronograma'],
            },
        ),
        migrations.AddField(
            model_name='grupocarreraexamen',
            name='grupofacultad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoFacultadExamen', verbose_name='grupofacultad'),
        ),
        migrations.AddField(
            model_name='asignacioncoordinadordocente',
            name='grupocarrera',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraExamen', verbose_name='grupocarrera'),
        ),
        migrations.AddField(
            model_name='asignacioncoordinadordocente',
            name='periodo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='asignacioncoordinadordocente',
            name='persona',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='persona'),
        ),
        migrations.AddField(
            model_name='asignacioncoordinadordocente',
            name='tiporeactivo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.TipoReactivo', verbose_name='tiporeactivo'),
        ),
    ]
