# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0008_asignacioncoordinadordocente_tamaniobateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaplanificacionexamen',
            name='porcsimilitud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de similitud'),
        ),
    ]
