# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0010_asignacioncoordinadordocente_activoasignar'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncoordinadordocente',
            name='estadorevision',
            field=models.NullBooleanField(default=True, verbose_name='estadorevision'),
        ),
    ]
