# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0012_asignacioncoordinadordocente_estadoasignar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncoordinadordocente',
            name='estadoasignar',
            field=models.NullBooleanField(default=True, verbose_name='estadoasignar'),
        ),
    ]
