# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0013_auto_20200820_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncoordinadordocente',
            name='estadoasignar',
            field=models.NullBooleanField(default=False, verbose_name='estadoasignar'),
        ),
        migrations.AlterField(
            model_name='asignacioncoordinadordocente',
            name='estadofinal',
            field=models.NullBooleanField(default=False, verbose_name='estadofinal'),
        ),
        migrations.AlterField(
            model_name='asignacioncoordinadordocente',
            name='estadorevision',
            field=models.NullBooleanField(default=False, verbose_name='estadorevision'),
        ),
    ]
