# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0014_auto_20200820_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDocenteReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='nombre')),
                ('inicio', models.DateTimeField(verbose_name='inicio')),
                ('fin', models.DateTimeField(verbose_name='fin')),
                ('estadoinicial', models.NullBooleanField(default=True, verbose_name='estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=False, verbose_name='estadofinal')),
                ('revision', models.NullBooleanField(default=False, verbose_name='estadofinal')),
                ('cantidad', models.IntegerField(default='10', verbose_name='cantidad')),
                ('activo', models.NullBooleanField(default=False, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'AsignacionDocenteReactivo',
                'verbose_name_plural': 'AsignacionDocenteReactivos',
            },
        ),
        migrations.CreateModel(
            name='ReactivoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('activo', models.NullBooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'ReactivoArea',
                'verbose_name_plural': 'ReactivoAreas',
            },
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.ReactivoArea', verbose_name='area'),
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='asignacion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignacionCoordinadorDocente', verbose_name='asignacion'),
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='docente',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Profesor', verbose_name='docente'),
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='formato',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoFormatoReactivo', verbose_name='asignacion'),
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='materia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Materia', verbose_name='materia'),
        ),
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='persona',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='persona'),
        ),
    ]
