# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0015_auto_20200821_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocentereactivo',
            name='asignatura',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignaturaMalla', verbose_name='asignatura'),
        ),
    ]
