# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0016_asignaciondocentereactivo_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionGrupoCoordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('activoasignar', models.NullBooleanField(default=True, verbose_name='activo')),
                ('estadorevision', models.NullBooleanField(default=False, verbose_name='estadorevision')),
                ('estadoasignar', models.NullBooleanField(default=False, verbose_name='estadoasignar')),
                ('estadoinicial', models.NullBooleanField(default=True, verbose_name='estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=False, verbose_name='estadofinal')),
                ('tamaniobateria', models.IntegerField(blank=True, null=True, verbose_name='Tamanio bateria')),
                ('coordinador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.CoordinadorCarrera', verbose_name='coordinador')),
                ('formato', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoFormatoReactivo', verbose_name='formato')),
            ],
            options={
                'verbose_name': 'AsignacionGrupoCoordinador',
                'verbose_name_plural': 'AsignacionGrupoCoordinadores',
            },
        ),
        migrations.CreateModel(
            name='GrupoCarreraMallaExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grupocarreraexamen',
            name='activocarrera',
            field=models.NullBooleanField(default=False, verbose_name='activocarrera'),
        ),
        migrations.AddField(
            model_name='grupocarreraexamen',
            name='activomalla',
            field=models.NullBooleanField(default=False, verbose_name='activomalla'),
        ),
        migrations.AddField(
            model_name='grupocarreramallaexamen',
            name='grupocarrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraExamen', verbose_name='grupocarrera'),
        ),
        migrations.AddField(
            model_name='grupocarreramallaexamen',
            name='malla',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seg.Malla', verbose_name='malla'),
        ),
        migrations.AddField(
            model_name='asignaciongrupocoordinador',
            name='grupocarrera',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraExamen', verbose_name='grupocarrera'),
        ),
        migrations.AddField(
            model_name='asignaciongrupocoordinador',
            name='grupomalla',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraMallaExamen', verbose_name='grupomalla'),
        ),
        migrations.AddField(
            model_name='asignaciongrupocoordinador',
            name='periodo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='asignaciongrupocoordinador',
            name='persona',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Persona', verbose_name='persona'),
        ),
    ]
