# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0018_auto_20200918_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('aleatorio', models.NullBooleanField(default=True, verbose_name='opcionaleatorio')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('estadoinicial', models.NullBooleanField(default=True, verbose_name='Estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=True, verbose_name='Estadofinal')),
                ('observacion', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='observacion')),
            ],
            options={
                'verbose_name': 'Reactivo',
                'ordering': ['asignaciondocente'],
                'verbose_name_plural': 'Reactivos',
            },
        ),
        migrations.AlterModelOptions(
            name='asignaciondocentereactivo',
            options={'ordering': ['asignacion'], 'verbose_name': 'AsignacionDocenteReactivo', 'verbose_name_plural': 'AsignacionDocenteReactivos'},
        ),
        migrations.AddField(
            model_name='reactivodocente',
            name='asignaciondocente',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignacionDocenteReactivo', verbose_name='asignacion'),
        ),
        migrations.AddField(
            model_name='reactivodocente',
            name='tipopregunta',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.TipoPreguntaReactivo', verbose_name='tipopregunta'),
        ),
    ]
