# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0019_auto_20200925_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivodocente',
            name='estadofinal',
            field=models.NullBooleanField(default=False, verbose_name='Estadofinal'),
        ),
    ]
