# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0021_detallereactivodocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='BateriaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BateriaDetalle',
                'verbose_name_plural': 'BateriaDetalles',
            },
        ),
        migrations.CreateModel(
            name='BateriaExamenComplexivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('revision', models.NullBooleanField(default=False, verbose_name='revision')),
                ('estadoinicial', models.NullBooleanField(default=False, verbose_name='estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=False, verbose_name='estadofinal')),
                ('carrera', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraExamen', verbose_name='carrera')),
                ('coordinador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignacionGrupoCoordinador', verbose_name='periodo')),
                ('tiporeactivo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.TipoReactivo', verbose_name='tiporeactivo')),
            ],
            options={
                'verbose_name': 'BateriaExamenCompolexivo',
                'verbose_name_plural': 'BateriasExamenCompolexivo',
            },
        ),
        migrations.AddField(
            model_name='bateriadetalle',
            name='bateria',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaExamenComplexivo', verbose_name='bateria'),
        ),
        migrations.AddField(
            model_name='bateriadetalle',
            name='reactivo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.ReactivoDocente', verbose_name='reactivo'),
        ),
    ]
