# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0024_bateriacarrera_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='BateriaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('bateriacarrera', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaCarrera', verbose_name='bateriacarrera')),
                ('matricula', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.MatriculaTitulacion', verbose_name='matricula')),
                ('periodo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'BateriaDetalle',
                'verbose_name_plural': 'BateriaDetalles',
            },
        ),
    ]
