# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0026_auto_20201030_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('tiempo', models.IntegerField(blank=True, null=True, verbose_name='tiempo')),
                ('carrera', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoCarreraExamen', verbose_name='carrera')),
                ('periodo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Periodo', verbose_name='periodo')),
                ('planificacion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.CronogramaPlanificacionExamen', verbose_name='planificacion')),
            ],
            options={
                'verbose_name_plural': 'CronogramaExamenes',
                'verbose_name': 'CronogramaExamen',
            },
        ),
    ]
