# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0028_cronogramaexamen_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaexamen',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
