# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0029_auto_20201105_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('aula', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='fecha')),
                ('inicio', models.TimeField(blank=True, null=True, verbose_name='inicio')),
                ('fin', models.TimeField(blank=True, null=True, verbose_name='inicio')),
                ('minutos', models.IntegerField(blank=True, null=True, verbose_name='tiempo')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='cantidad')),
                ('notamin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='notamin')),
                ('notamax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='notamax')),
                ('tipoexamen', models.IntegerField(blank=True, choices=[(1, 'ALEATORIO'), (2, 'RANGO'), (3, 'AREA-MATERIA')], default=1, null=True, verbose_name='Tipo de examen')),
                ('cronogramaexamen', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.CronogramaExamen', verbose_name='cronogramaexamen')),
            ],
            options={
                'verbose_name': 'Grupoexamen',
                'verbose_name_plural': 'Grupoexamenes',
            },
        ),
        migrations.CreateModel(
            name='GrupoExamenConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='cantidad')),
                ('rangoinicio', models.IntegerField(blank=True, null=True, verbose_name='rangoinicio')),
                ('rangofin', models.IntegerField(blank=True, null=True, verbose_name='rangofin')),
                ('aleatorio', models.NullBooleanField(verbose_name='aleatorio')),
                ('tipoexamen', models.IntegerField(blank=True, choices=[(1, 'COMPLETO'), (2, 'SECCION')], default=1, null=True, verbose_name='Tipo de aleatorio')),
                ('area', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.ReactivoArea', verbose_name='area')),
                ('asignatura', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignaturaMalla', verbose_name='asignatura')),
                ('bateria', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaCarrera', verbose_name='bateria')),
                ('grupoexamen', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamen', verbose_name='grupoexamen')),
            ],
            options={
                'verbose_name': 'GrupoExamenConfiguracion',
                'verbose_name_plural': 'GrupoExamenConfiguraciones',
            },
        ),
        migrations.CreateModel(
            name='GrupoExamenDelegado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('principal', models.NullBooleanField(default=True, verbose_name='activo')),
                ('docente', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Profesor', verbose_name='docente')),
                ('grupoexamen', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamen', verbose_name='grupoexamen')),
            ],
            options={
                'verbose_name': 'GrupoExamenDelegado',
                'verbose_name_plural': 'GrupoExamenDelegados',
            },
        ),
        migrations.CreateModel(
            name='GrupoExamenEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estadoinicial', models.NullBooleanField(default=False, verbose_name='estadoinicial')),
                ('estadofinal', models.NullBooleanField(default=False, verbose_name='estadofinal')),
                ('activo', models.NullBooleanField(default=True, verbose_name='activo')),
                ('estudiante', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.MatriculaTitulacion', verbose_name='estudiante')),
                ('grupoconfiguracion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamenConfiguracion', verbose_name='grupoconfiguracion')),
            ],
            options={
                'verbose_name': 'GrupoExamenEstudiante',
                'verbose_name_plural': 'GrupoExamenEstudiantes',
            },
        ),
    ]
