# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0030_grupoexamen_grupoexamenconfiguracion_grupoexamendelegado_grupoexamenestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoexamen',
            name='tiposeleccion',
            field=models.IntegerField(blank=True, choices=[(1, 'ALEATORIO'), (2, 'RANGO'), (3, 'AREA-MATERIA')], default=1, null=True, verbose_name='Tipo de seleccion'),
        ),
        migrations.AlterField(
            model_name='grupoexamen',
            name='tipoexamen',
            field=models.IntegerField(blank=True, choices=[(1, 'AVANZAR Y RETROCEDER'), (2, 'AVANZAR'), (2, 'TIEMPO')], default=1, null=True, verbose_name='Tipo de examen'),
        ),
    ]
