# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0031_auto_20201107_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoexamenconfiguracion',
            name='tiposeleccion',
            field=models.IntegerField(blank=True, choices=[(1, 'ALEATORIO'), (2, 'RANGO'), (3, 'AREA-MATERIA')], default=1, null=True, verbose_name='Tipo de seleccion'),
        ),
    ]
