# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0032_grupoexamenconfiguracion_tiposeleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='tipoexamen',
        ),
        migrations.AddField(
            model_name='grupoexamenconfiguracion',
            name='filtroseleccion',
            field=models.IntegerField(blank=True, choices=[(1, 'COMPLETO'), (2, 'SECCION')], default=1, null=True, verbose_name='Filtro de seleccion'),
        ),
    ]
