# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0033_auto_20201108_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoexamenestudiante',
            name='grupoconfiguracion',
        ),
        migrations.AddField(
            model_name='grupoexamenestudiante',
            name='bateria',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaCarrera', verbose_name='bateria'),
        ),
        migrations.AddField(
            model_name='grupoexamenestudiante',
            name='grupoexamen',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamen', verbose_name='grupoexamen'),
        ),
    ]
