# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0034_auto_20201108_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='cantidad')),
                ('rangoinicio', models.IntegerField(blank=True, null=True, verbose_name='rangoinicio')),
                ('rangofin', models.IntegerField(blank=True, null=True, verbose_name='rangofin')),
                ('aleatorio', models.NullBooleanField(verbose_name='aleatorio')),
                ('area', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.ReactivoArea', verbose_name='area')),
                ('asignatura', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.AsignaturaMalla', verbose_name='asignatura')),
            ],
            options={
                'verbose_name_plural': 'GrupoConfiguraciones',
                'verbose_name': 'GrupoConfiguracion',
            },
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='aleatorio',
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='area',
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='rangofin',
        ),
        migrations.RemoveField(
            model_name='grupoexamenconfiguracion',
            name='rangoinicio',
        ),
        migrations.RemoveField(
            model_name='grupoexamenestudiante',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='grupoexamenestudiante',
            name='grupoexamen',
        ),
        migrations.AddField(
            model_name='grupoexamenestudiante',
            name='grupoexamenconfiguracion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamenConfiguracion', verbose_name='grupoexamenconfiguracion'),
        ),
        migrations.AlterField(
            model_name='grupoexamen',
            name='tiposeleccion',
            field=models.IntegerField(blank=True, choices=[(1, 'ALEATORIO'), (2, 'RANGO'), (3, 'AREA-MATERIA')], null=True, verbose_name='Tipo de seleccion'),
        ),
        migrations.AlterField(
            model_name='grupoexamenestudiante',
            name='activo',
            field=models.NullBooleanField(default=False, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='grupoconfiguracion',
            name='grupoexamenconfiguracion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamenConfiguracion', verbose_name='grupoexamenconfiguracion'),
        ),
    ]
