# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0035_auto_20201109_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoexamendelegado',
            name='tipodelegado',
            field=models.IntegerField(blank=True, choices=[(1, 'UPA'), (2, 'CARRERA')], default=1, null=True, verbose_name='Tipo de delegado'),
        ),
    ]
