# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0036_grupoexamendelegado_tipodelegado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEstudianteExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('emparejamiento', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.DetalleReactivoDocente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteExamenReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.NullBooleanField(default=None, verbose_name='estado')),
                ('revision', models.NullBooleanField(default=False, verbose_name='revision')),
                ('bateriadetalle', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaDetalle', verbose_name='bateriadetalle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grupoexamenestudiante',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='estudianteexamenreactivo',
            name='grupoexamenestudiante',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamenEstudiante', verbose_name='grupoexamenestudiante'),
        ),
        migrations.AddField(
            model_name='detalleestudianteexamen',
            name='reactivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.EstudianteExamenReactivo'),
        ),
    ]
