# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0038_auto_20201113_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoconfiguracion',
            name='notamax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='notamax'),
        ),
        migrations.AddField(
            model_name='grupoconfiguracion',
            name='notamin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='notamin'),
        ),
        migrations.AddField(
            model_name='grupoconfiguracion',
            name='tiporeactivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.TipoReactivo', verbose_name='tiporeactivo'),
        ),
    ]
