# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-13 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0039_auto_20201113_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoconfiguracion',
            name='notamax',
        ),
        migrations.RemoveField(
            model_name='grupoconfiguracion',
            name='notamin',
        ),
    ]
