# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0042_formatoreactivo_valiopciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('emparejamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.DetalleReactivoDocente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulacionExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='cantidad')),
                ('bateriacarrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaCarrera')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulacionExamenReactivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.NullBooleanField(default=None, verbose_name='estado')),
                ('detallebateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.BateriaDetalle')),
                ('simulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.SimulacionExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='simulaciondetalle',
            name='reactivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.SimulacionExamenReactivo'),
        ),
    ]
