# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0043_auto_20201117_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacionexamen',
            name='persona',
        ),
        migrations.AddField(
            model_name='simulacionexamen',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.MatriculaTitulacion'),
        ),
    ]
