# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0047_auto_20201119_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='impugnacionexamen',
            name='estado',
            field=models.NullBooleanField(default=None, verbose_name='estado'),
        ),
    ]
