# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0048_impugnacionexamen_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impugnaciondetalle',
            name='reactivo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.EstudianteExamenReactivo', verbose_name='reactivo'),
        ),
    ]
