# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-12-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seg', '0049_auto_20201120_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoexamenestudiante',
            name='grupoexamen',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seg.GrupoExamen', verbose_name='grupoexamen'),
        ),
    ]
